[package]
name = "sailas_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sailasm = { path = "../sailasm" }
sailar = { path = "../sailar" }
wasm-bindgen = "0.2.80"
js-sys = "0.3.57"
console_error_panic_hook = "0.1.7"
