[package]
name = "asmdl_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.1.3"
asmdl = { path = "../asmdl" }
structopt = "0.3.25"
sailar = { path = "../sailar" }

[[bin]]
name = "asmdl"
path = "src/main.rs"
