[package]
name = "sailas"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.1.3"
sailar_asm = { path = "../sailar_asm" }
structopt = "0.3.25"
sailar = { path = "../sailar" }

[[bin]]
name = "sailas"
path = "src/main.rs"
