[package]
name = "sailar_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
sailar = { path = "../sailar" }
sailar_get = { path = "../sailar_get" }
thiserror = "1.0.30"

[dev-dependencies]
sailar_asm = { path = "../sailar_asm" }
