[package]
name = "sailar_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
sailar = { path = "../sailar" }
sailar_load = { path = "../sailar_load" }
thiserror = "1.0.30"

[dev-dependencies]
sailar_samples = { path = "../sailar_samples" }
