[package]
name = "runmdl"
version = "0.1.0"
edition = "2021"

[dependencies]
getmdl = { path = "../getmdl" }
registir = { path = "../registir" }
thiserror = "1.0.30"

[dev-dependencies]
asmdl = { path = "../asmdl" }
