[package]
name = "dasmdl_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dasmdl = { path = "../dasmdl" }
sailar = { path = "../sailar" }
structopt = "0.3.25"

[[bin]]
name = "dasmdl"
path = "src/main.rs"
