[package]
name = "sailar"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.60"

[dependencies]
bitflags = "1.3.2"
elsa = "1.7.0"
rustc-hash = "1.1.0"
sha2 = "0.10.1"
thiserror = "1.0.30"
